resources:
- name: webmon-git
  type: git
  source:
    branch: master
    uri: https://github.com/jelledrm/weblogic-monitoring.git

- name: Artifactory
  type: docker-image
  source:
    email: jelle2510@gmail.com
    repository: docker.artifactory:80/webmon
    username: admin
    password: admin
    insecure_registries:
    - docker.artifactory:80

jobs:
 - name: build-webmon
   plan:
   - get: webmon-git
     trigger: true
   - task : Build Code
     config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: joepjoosten/openjdk-alpine-bash
        inputs:
        - name: webmon-git
        outputs:
        - name: webmon-build-output
        run:
          path: sh
          args:
            - -exc
            - |
              export TERM=dumb
              cd webmon-git
              chmod +x gradlew
              ./gradlew createDockerfile
              cp build/docker/Dockerfile ../webmon-build-output
              cp build/libs/weblogic-monitoring-0.0.1-SNAPSHOT.jar ../webmon-build-output
   - task: push-to-artifactory
     config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: busybox
        inputs:
        - name: webmon-build-output
        run:
          path: sh
          args:
            - -exc
            - |
              ls -R
   - put: Artifactory
     params:
      build: ./webmon-build-output

 - name: deploy-to-integration
   plan:
   - get: webmon-git
     passed: [build-webmon]
     trigger: true
   - task: Deploy container to TEST
     config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: joepjoosten/openjdk-alpine-bash
        inputs:
        - name: webmon-git
        outputs:
        - name: webmon-build-output
        run:
          path: sh
          args:
            - -exc
            - |
              export TERM=dumb
              cd webmon-git
              chmod +x gradlew
              ./gradlew startContainerForTest



